import { contentHash } from "@/lib/crypto";
import { prisma } from "@/lib/db";
import { DAY_MS } from "@/lib/time";
import type { ActionType } from "./actions";

/**
 * Suggesting what to do about a loop.
 *
 * Proposals are generated by rules, not by the model. The model's job was to
 * work out what the email meant; deciding that "a loop with a deadline could
 * use a reminder" needs no intelligence and would only add a way to propose
 * something incoherent. What the model *is* used for — writing the actual
 * words of a reply — happens later, on approval, when the user has asked for it.
 *
 * Nothing here executes. A proposal is an offer, and it stays inert until the
 * user approves it individually.
 */

export interface ProposedAction {
  type: ActionType;
  summary: string;
  payload: Record<string, unknown>;
  requiresApproval: boolean;
  idempotencyKey: string;
}

interface ProposalInput {
  id: string;
  title: string;
  category: string;
  dueAt: Date | null;
  counterpartyName: string | null;
  counterpartyEmail: string | null;
  status: string;
}

/** Categories where the outstanding step is literally "reply to a person". */
const REPLY_CATEGORIES = new Set(["unanswered_email", "follow_up", "commitment"]);

/** How far ahead of a deadline a reminder is actually useful. */
const REMINDER_LEAD_MS = DAY_MS;

export function proposalsFor(loop: ProposalInput, now: Date = new Date()): ProposedAction[] {
  if (loop.status !== "open") return [];
  const proposals: ProposedAction[] = [];

  // A reminder only helps if there is still time to act on it.
  if (loop.dueAt) {
    const remindAt = new Date(loop.dueAt.getTime() - REMINDER_LEAD_MS);
    if (remindAt.getTime() > now.getTime()) {
      proposals.push({
        type: "create_reminder",
        summary: `Remind you about "${loop.title}" the day before it is due.`,
        payload: { remindAt: remindAt.toISOString(), loopId: loop.id },
        // Confined to Luma: it creates a notification and nothing else.
        requiresApproval: false,
        idempotencyKey: contentHash("reminder", loop.id, remindAt.toISOString()),
      });
    }
  }

  // Only offer to draft when there is a specific person to reply to.
  if (REPLY_CATEGORIES.has(loop.category) && loop.counterpartyEmail) {
    proposals.push({
      type: "draft_email",
      summary: `Draft a reply to ${loop.counterpartyName ?? loop.counterpartyEmail}. Nothing is sent — you review it first.`,
      payload: {
        loopId: loop.id,
        to: loop.counterpartyEmail,
        toName: loop.counterpartyName,
      },
      requiresApproval: true,
      idempotencyKey: contentHash("draft", loop.id, loop.counterpartyEmail),
    });
  }

  return proposals;
}

/**
 * Writes proposals for a loop, skipping any that already exist.
 *
 * The idempotency key is derived from the loop and the proposal's substance,
 * so re-running after a sync cannot pile up duplicate offers — and a proposal
 * the user already rejected is not silently resurrected.
 */
export async function proposeForLoop(
  userId: string,
  loop: ProposalInput,
  now: Date = new Date(),
): Promise<number> {
  const proposals = proposalsFor(loop, now);
  let created = 0;

  for (const proposal of proposals) {
    try {
      await prisma.action.create({
        data: {
          userId,
          loopId: loop.id,
          type: proposal.type,
          status: "proposed",
          summary: proposal.summary,
          payload: JSON.stringify(proposal.payload),
          requiresApproval: proposal.requiresApproval,
          idempotencyKey: proposal.idempotencyKey,
        },
      });
      created += 1;
    } catch {
      // Unique violation on idempotencyKey: already proposed. Leave it alone —
      // re-proposing something the user rejected would be nagging.
    }
  }

  return created;
}

/** Generates proposals for every open loop a user has. */
export async function proposeForUser(userId: string, now: Date = new Date()): Promise<number> {
  const loops = await prisma.openLoop.findMany({
    where: { userId, status: "open" },
    select: {
      id: true,
      title: true,
      category: true,
      dueAt: true,
      counterpartyName: true,
      counterpartyEmail: true,
      status: true,
    },
  });

  let created = 0;
  for (const loop of loops) created += await proposeForLoop(userId, loop, now);
  return created;
}
